Rails.application.routes.draw do
  # Generated by devise
  devise_for :users

  # Root page
  root to: "pages#home"

  # Cart routes
  resources :cart, only: [:show]
  post 'cart/add'
  post 'cart/remove'
  post 'cart/make_payment'
  get 'cart/success'
  get 'cart/cancel'

  # Checkout routes
  post 'checkout/create', to: 'checkouts#create'

  # User routes
  resources :users

  # Event + event booking routes
  resources :events do
    resources :event_bookings, only: [:create]
  end
  resources :event_bookings, only: [:destroy]

  # Routes for shops (unfinished)
  resources :shops
end
